import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "The terms governing your use of CreatorDevTools.",
  alternates: { canonical: "/terms" },
};

export default function TermsPage() {
  return (
    <div className="mx-auto max-w-3xl px-4 py-10 sm:px-6 lg:px-8 prose prose-slate dark:prose-invert max-w-none">
      <h1>Terms of Service</h1>
      <p>Last updated: January 2025</p>

      <h2>Acceptance of terms</h2>
      <p>
        By using CreatorDevTools, you agree to these Terms of Service. If you do not agree,
        please do not use the site.
      </p>

      <h2>Use of the service</h2>
      <p>
        CreatorDevTools provides free browser-based and AI-assisted tools &ldquo;as is,&rdquo;
        without warranty of any kind. You are responsible for reviewing any AI-generated content
        before publishing or relying on it — AI output can be inaccurate or unsuitable for your
        specific use case.
      </p>

      <h2>Acceptable use</h2>
      <p>You agree not to use this site to:</p>
      <ul>
        <li>Generate content that is illegal, fraudulent, or infringes on others&apos; rights</li>
        <li>Attempt to abuse, overload, or circumvent rate limits on our AI tools</li>
        <li>Attempt to extract, reverse-engineer, or misuse our system prompts or infrastructure</li>
        <li>Use automated means to scrape or bulk-generate content beyond normal personal use</li>
      </ul>

      <h2>No guaranteed availability</h2>
      <p>
        We aim to keep tools available and functioning, but we do not guarantee uninterrupted
        access. AI-powered tools depend on third-party providers and may be temporarily
        unavailable.
      </p>

      <h2>Intellectual property</h2>
      <p>
        The CreatorDevTools name, branding, and site design are owned by us. Output generated by
        our tools based on your own input is yours to use.
      </p>

      <h2>Limitation of liability</h2>
      <p>
        To the fullest extent permitted by law, CreatorDevTools is not liable for any damages
        arising from your use of the site or reliance on tool output, including AI-generated
        content.
      </p>

      <h2>Changes to these terms</h2>
      <p>
        We may update these Terms from time to time. Continued use of the site after changes
        constitutes acceptance of the updated terms.
      </p>

      <h2>Contact us</h2>
      <p>
        Questions about these terms? Reach out via our <a href="/contact">contact page</a>.
      </p>
    </div>
  );
}
